### ISSUE TITLE
Can't run validation on whole corpus localy (Java OutOfMemoryError)

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#482]
When I try to run make val-schema-ana-IS I get an OutOfMemoryError. Is there any simple way to bypass this?

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3793)
	at net.sf.saxon.tree.tiny.TinyTree.ensureNodeCapacity(TinyTree.java:232)
	at net.sf.saxon.tree.tiny.TinyTree.addNode(TinyTree.java:339)
	at net.sf.saxon.tree.tiny.TinyBuilder.startElement(TinyBuilder.java:270)
	at net.sf.saxon.event.Stripper.startElement(Stripper.java:114)
	at net.sf.saxon.event.ReceivingContentHandler.startElement(ReceivingContentHandler.java:379)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.startElement(XIncludeHandler.java:1001)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.handleIncludeElement(XIncludeHandler.java:1826)
	at java.xml/com.sun.org.apache.xerces.internal.xinclude.XIncludeHandler.emptyElement(XIncludeHandler.java:1032)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
	at net.sf.saxon.event.Sender.send(Sender.java:168)
	at net.sf.saxon.Configuration.buildDocumentTree(Configuration.java:4203)
	at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:357)
	at net.sf.saxon.Transform.processFile(Transform.java:1290)
WARNING skipping/failing val-schema-ana-ParlaCLARIN-IS
`

**Comment by TomazErjavec** [comment]
The way I do it is
```
java -Xmx120g -jar /usr/share/java/saxon.jar ...
```

**Comment by starkadur** [comment]
But I am using the command:
`make val-schema-ana-IS`

How do I pass the -xmx to the makefile? Or do I have to change the makefile? Or bypass the makefile altogether?

**Comment by TomazErjavec** [comment]
Hm yes, good point. I think this one is then for @matyaskopp, maybe the best would be to increas heap directly in the makefile. Or, if in a hurry, you do it yourself, I guess here:
https://github.com/clarin-eric/ParlaMint/blob/c5fd7aaee29b18cf537a84850d41c4930250de51/Makefile#L641

**Comment by matyaskopp** [comment]
@starkadur the target `val-schema-ana-IS` is running these targets: `val-schema-ana-ParlaMint-IS` and `val-schema-ana-ParlaCLARIN-IS`. The problem is caused by ParlaClarin validation part because it firstly includes all component files into a root.

You can skip ParlaCLARIN schema validation and run just:
```bash
make val-schema-ana-ParlaMint-IS
```

> Hm yes, good point. I think this one is then for @matyaskopp, maybe the best would be to increas heap directly in the makefile

Ok I will take a look. I will probably add passing the settings by another parameter, I am not sure if java allows larger heap size than computer memory.

**Comment by starkadur** [comment]
Thanks, works fine if I use 
`make val-schema-ana-ParlaMint-IS`
